### ISSUE TITLE
 Not working on OneUI 5.1.1

### ISSUE THREAD

**Issue by atnoir** [moneytoo/Runner#3]
After my tablet upgrades to OneUI 5.1.1, it stops working that tapping it brings no additional apps to update. All hibernated apps are still disabled.

**Comment by atnoir** [comment]
Solution found: after OneUi 5.1.1, it's required to grant permission to apps' list to make it work. Runner doesn't request this permission by itself, and so it takes some manual steps.

**Comment by atnoir** [comment]
Solution found: after OneUi 5.1.1, it's required to grant permission to apps' list to make it work. Runner doesn't request this permission by itself, and so it takes some manual steps.

**Comment by privacyguy123** [comment]
> Solution found: after OneUi 5.1.1, it's required to grant permission to apps' list to make it work. Runner doesn't request this permission by itself, and so it takes some manual steps.

How did you manually grant the permission?
